/**
 *    Copyright ${license.git.copyrightYears} the original author or authors.
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */
package com.banma.aloha.model;


import java.util.Date;

/**
 * aloha_user_fact
 * 实体类对应的数据表为：  aloha_user_fact
 * @author xingjun
 * @date Wed Mar 21 15:45:31 CST 2018
 */
public class UserFact
{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aloha_user_fact.id
     *
     * @mbg.generated Wed Mar 21 15:45:31 CST 2018
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   人员id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aloha_user_fact.user_id
     *
     * @mbg.generated Wed Mar 21 15:45:31 CST 2018
     */
    private Integer userId;

    /**
     * Database Column Remarks:
     *   行为记录id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aloha_user_fact.fact_id
     *
     * @mbg.generated Wed Mar 21 15:45:31 CST 2018
     */
    private Integer factId;

    /**
     * Database Column Remarks:
     *   删除标志：0-有效；1-删除
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aloha_user_fact.delete_flag
     *
     * @mbg.generated Wed Mar 21 15:45:31 CST 2018
     */
    private Integer deleteFlag;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aloha_user_fact.update_time
     *
     * @mbg.generated Wed Mar 21 15:45:31 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aloha_user_fact
     *
     * @mbg.generated Wed Mar 21 15:45:31 CST 2018
     */
    public UserFact(Integer id, Integer userId, Integer factId, Integer deleteFlag, Date updateTime) {
        this.id = id;
        this.userId = userId;
        this.factId = factId;
        this.deleteFlag = deleteFlag;
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aloha_user_fact
     *
     * @mbg.generated Wed Mar 21 15:45:31 CST 2018
     */
    public UserFact() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aloha_user_fact.id
     *
     * @return the value of aloha_user_fact.id
     *
     * @mbg.generated Wed Mar 21 15:45:31 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aloha_user_fact.id
     *
     * @param id the value for aloha_user_fact.id
     *
     * @mbg.generated Wed Mar 21 15:45:31 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aloha_user_fact.user_id
     *
     * @return the value of aloha_user_fact.user_id
     *
     * @mbg.generated Wed Mar 21 15:45:31 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aloha_user_fact.user_id
     *
     * @param userId the value for aloha_user_fact.user_id
     *
     * @mbg.generated Wed Mar 21 15:45:31 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aloha_user_fact.fact_id
     *
     * @return the value of aloha_user_fact.fact_id
     *
     * @mbg.generated Wed Mar 21 15:45:31 CST 2018
     */
    public Integer getFactId() {
        return factId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aloha_user_fact.fact_id
     *
     * @param factId the value for aloha_user_fact.fact_id
     *
     * @mbg.generated Wed Mar 21 15:45:31 CST 2018
     */
    public void setFactId(Integer factId) {
        this.factId = factId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aloha_user_fact.delete_flag
     *
     * @return the value of aloha_user_fact.delete_flag
     *
     * @mbg.generated Wed Mar 21 15:45:31 CST 2018
     */
    public Integer getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aloha_user_fact.delete_flag
     *
     * @param deleteFlag the value for aloha_user_fact.delete_flag
     *
     * @mbg.generated Wed Mar 21 15:45:31 CST 2018
     */
    public void setDeleteFlag(Integer deleteFlag) {
        this.deleteFlag = deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aloha_user_fact.update_time
     *
     * @return the value of aloha_user_fact.update_time
     *
     * @mbg.generated Wed Mar 21 15:45:31 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aloha_user_fact.update_time
     *
     * @param updateTime the value for aloha_user_fact.update_time
     *
     * @mbg.generated Wed Mar 21 15:45:31 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}